# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил:
- Тептин Владислав Александрович
- АИС-21-1

| Задание | Лаб_раб | Сам_раб |
| ------ | ------ | ------ |
| Задание 1 | + | + |
| Задание 2 | + | + |
| Задание 3 | + | + |
| Задание 4 | + | + |
| Задание 5 | + | + |
| Задание 6 | + |  
| Задание 7 | + |  
| Задание 8 | + |  
| Задание 9 | + |  
| Задание 10 | + |  


## Самостоятельная работа №1
### Вовочка решил заняться спортивным программированием на python, но для этого он должен знать за какое время выполняется его программа. Он решил, что для этого ему идеально подойдет декоратор для функции, который будет выяснять за какое время выполняется та или иная функция. Помогите Вовочке в его начинаниях и напишите такой декоратор.

```python
import time

def calculate_time(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"\nФункция {func.__name__} выполнялась {end_time - start_time} секунд")
        return result
    return wrapper

@calculate_time
def fibonacci():
    fib1 = fib2 = 1
    for i in range(2, 200):
        fib1, fib2 = fib2, fib1 + fib2
        print(fib2, end=' ')

if __name__ == '__main__':
    fibonacci()
```
### Результат.
![Меню](https://github.com/boogeyman144/origin/blob/Тема_10/Pic/Tema10_1.png)

## Вывод
Я попрактиковался в создании декоратора, который считает время выполнения программы
  
## Самостоятельная работа №2
### Посмотрев на Вовочку, вы также загорелись идеей спортивного программирования, начав тренировки вы узнали, что для решения некоторых задач необходимо считывать данные из файлов. Но через некоторое время вы столкнулись с проблемой что файлы бывают пустыми, и вы не получаете вводные данные для решения задачи. После этого вы решили не просто считывать данные из файла, а всю конструкцию оборачивать в исключения, чтобы избежать такой проблемы. Создайте пустой файл и файл, в котором есть какая-то информация. Напишите код программы. Если файл пустой, то, нужно вызвать исключение (“бросить исключение”) и вывести в консоль “файл пустой”, а если он не пустой, то вывести информацию из файла.

```python
def read_file(filename):
    try:
        with open(filename, 'r') as file:
            content = file.read()
            if not content:
                raise Exception("Файл пустой")
            else:
                print("Информация из файла:")
                print(content)
    except FileNotFoundError:
        print("Файл не найден")
    except Exception as e:
        print(e)

# Проверяем пустой файл
print("Чтение файла:")
read_file('test.txt')
```
### Результат.
![Меню](https://github.com/boogeyman144/origin/blob/Тема_10/Pic/Tema10_2.png)
![Меню](https://github.com/boogeyman144/origin/blob/Тема_10/Pic/Tema10_2(2).png)

## Вывод
  Я попрактиковался в работе с исключениями
  
## Самостоятельная работа №3
Напишите функцию, которая будет складывать 2 и введенное пользователем число, но если пользователь введет строку или другой неподходящий тип данных, то в консоль выведется ошибка “Неподходящий тип данных. Ожидалось число.”. Реализовать функционал программы необходимо через try/except и подобрать правильный тип исключения. Создавать собственное исключение нельзя. Проведите несколько тестов, в которых исключение вызывается и нет. Результатом выполнения задачи будет листинг кода и получившийся вывод в консоль

```python
def add_two_to_input():
    try:
        user_input = input("Введите число: ")
        result = 2 + int(user_input)
        print("Результат сложения:", result)
    except ValueError:
        print("Неподходящий тип данных. Ожидалось целое число.")
add_two_to_input()
add_two_to_input()
add_two_to_input()

```
### Результат.
![Меню](https://github.com/boogeyman144/origin/blob/Тема_10/Pic/Tema10_3.png)

## Самостоятельная работа №4
### Создайте собственный декоратор, который будет использоваться для двух любых вами придуманных функций.

```python
# Декоратор, который печатает сообщение
def print_message_decorator(func):
    def wrapper(*args, **kwargs):
        print("Декоратор печатает это сообщение")
        return func(*args, **kwargs)
    return wrapper

# Функции, которые используют данный декоратор
@print_message_decorator
def say_hello():
    print("Hello, world!")

@print_message_decorator
def multiply(a, b):
    return a * b

if __name__ == "__main__":
    say_hello()  # Вызываем функцию say_hello
    result = multiply(5, 7)  # Вызываем функцию multiply
    print("Результат умножения:", result)
```
### Результат.
![Меню](https://github.com/boogeyman144/origin/blob/Тема_10/Pic/Tema10_4.png)

 
## Самостоятельная работа №5
### Создайте собственное исключение, которое будет использоваться в двух любых фрагментах кода.

```python
# Создаем собственное исключение
class InvalidInputError(Exception):
    pass

# Пример использования исключения в первом фрагменте кода
def process_user_input(value):
    try:
        if not isinstance(value, int):
            raise InvalidInputError("Ожидалось целое число")
        result = value * 2
        print(f"Результат удвоения введенного числа: {result}")
    except InvalidInputError as e:
        print(f"Ошибка: {e}")

# Пример использования исключения во втором фрагменте кода
def calculate_square_root(number):
    try:
        if number < 0:
            raise InvalidInputError("Нельзя извлечь корень из отрицательного числа")
        result = number ** 0.5
        print(f"Квадратный корень из числа {number}: {result}")
    except InvalidInputError as e:
        print(f"Ошибка: {e}")

if __name__ == "__main__":
    # Первый фрагмент кода
    process_user_input(10)  # Правильный ввод
    process_user_input("abc")  # Некорректный ввод, вызов исключения

    print("\n===========================================\n")

    # Второй фрагмент кода
    calculate_square_root(25)  # Правильный ввод
    calculate_square_root(-9)  # Некорректный ввод, вызов исключения
```
### Результат.
![Меню](https://github.com/boogeyman144/origin/blob/Тема_10/Pic/Tema10_5.png)
